# ABOUTME: Auto-analysis models for constraint-based SDF region detection
# ABOUTME: Defines generated constraints from multiple algorithms and analysis results

from datetime import UTC, datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class AlgorithmType(str, Enum):
    """Available auto-analysis algorithms."""

    POCKET = "pocket"  # Cavity detection via voxel flood-fill
    NORMAL_OFFSET = "normal_offset"  # Surface-relative offset regions
    FLOOD_FILL = "flood_fill"  # Exterior flood fill from sky for EMPTY regions
    VOXEL_REGIONS = "voxel_regions"  # Underground regions via voxel classification for SOLID boxes


# TODO: Re-enable pocket and normal_offset after testing flood_fill/voxel_regions
ALL_ALGORITHMS = [
    # AlgorithmType.POCKET,
    # AlgorithmType.NORMAL_OFFSET,
    AlgorithmType.FLOOD_FILL,
    AlgorithmType.VOXEL_REGIONS,
]


class GeneratedConstraint(BaseModel):
    """A constraint generated by auto-analysis, pending user approval.

    Wraps standard constraint data with algorithm metadata.
    """

    # The constraint itself (polymorphic - box, halfspace, pocket, etc.)
    constraint: dict = Field(..., description="Constraint data (type, sign, geometry)")

    # Metadata
    algorithm: AlgorithmType = Field(..., description="Algorithm that generated this")
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Algorithm's confidence in this constraint"
    )
    description: str = Field(..., description="Human-readable description")


class AlgorithmStats(BaseModel):
    """Statistics for a single algorithm's contribution."""

    constraints_generated: int = Field(0, description="Number of constraints from this algorithm")
    coverage_description: str = Field("", description="What this algorithm detected")


class AnalysisSummary(BaseModel):
    """Summary statistics for auto-analysis results."""

    total_constraints: int = Field(..., description="Total constraints generated")
    solid_constraints: int = Field(..., description="Constraints marking solid regions")
    empty_constraints: int = Field(..., description="Constraints marking empty regions")
    algorithms_contributing: int = Field(..., description="Number of algorithms that contributed")


class AutoAnalysisResult(BaseModel):
    """Complete auto-analysis result with generated constraints."""

    model_config = ConfigDict(ser_json_timedelta="iso8601")

    analysis_id: str = Field(..., description="Unique identifier for this analysis")
    computed_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="When analysis was performed",
    )
    algorithms_run: list[str] = Field(..., description="Algorithms that were executed")
    summary: AnalysisSummary = Field(..., description="Aggregated statistics")
    algorithm_stats: dict[str, AlgorithmStats] = Field(
        default_factory=dict, description="Per-algorithm statistics"
    )
    generated_constraints: list[GeneratedConstraint] = Field(
        default_factory=list, description="Constraints ready for user review"
    )


class AutoAnalyzeRequest(BaseModel):
    """Request parameters for auto-analysis."""

    algorithms: list[str] | None = Field(
        default=None,
        description="Algorithms to run (default: all). Options: pocket, normal_offset, flood_fill, voxel_regions",
    )
    recompute: bool = Field(
        default=False, description="Force recomputation even if cached results exist"
    )


class ApplyConstraintsRequest(BaseModel):
    """Request to apply selected generated constraints."""

    constraint_indices: list[int] = Field(
        ..., description="Indices of generated constraints to apply"
    )
