# ABOUTME: Auto-analysis models for constraint-based SDF region detection
# ABOUTME: Defines generated constraints from multiple algorithms and analysis results

from datetime import UTC, datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class AlgorithmType(str, Enum):
    """Available auto-analysis algorithms."""

    POCKET = "pocket"  # Cavity detection via voxel flood-fill
    NORMAL_OFFSET = "normal_offset"  # Surface-relative offset regions
    FLOOD_FILL = "flood_fill"  # Exterior flood fill from sky for EMPTY regions
    VOXEL_REGIONS = "voxel_regions"  # Underground regions via voxel classification for SOLID boxes
    NORMAL_IDW = "normal_idw"  # Inverse distance weighted normal sampling


ALL_ALGORITHMS = [
    AlgorithmType.POCKET,
    AlgorithmType.NORMAL_OFFSET,
    AlgorithmType.FLOOD_FILL,
    AlgorithmType.VOXEL_REGIONS,
    AlgorithmType.NORMAL_IDW,
]


class AutoAnalysisOptions(BaseModel):
    """Tunable hyperparameters for auto-analysis algorithms."""

    # Voxel grid parameters
    min_gap_size: float = Field(
        default=0.10,
        ge=0.01,
        le=1.0,
        description="Minimum gap size in meters that flood fill can traverse",
    )
    max_grid_dim: int = Field(
        default=200, ge=50, le=500, description="Maximum voxel grid dimension"
    )

    # Ray propagation
    cone_angle: float = Field(
        default=15.0, ge=0.0, le=45.0, description="Ray propagation cone half-angle in degrees"
    )

    # Normal offset
    normal_offset_pairs: int = Field(
        default=40,
        ge=10,
        le=200,
        description="Number of SOLID/EMPTY box pairs for normal_offset algorithm",
    )

    # Filtering
    max_boxes: int = Field(default=15, ge=5, le=100, description="Maximum boxes per algorithm")
    overlap_threshold: float = Field(
        default=0.5,
        ge=0.1,
        le=0.9,
        description="Fraction overlap required to remove redundant boxes",
    )

    # IDW Normal sampling
    idw_sample_count: int = Field(
        default=1000, ge=100, le=10000, description="Total IDW samples to generate"
    )
    idw_max_distance: float = Field(
        default=0.5, ge=0.05, le=2.0, description="Maximum distance from surface in meters"
    )
    idw_power: float = Field(
        default=2.0,
        ge=0.5,
        le=4.0,
        description="IDW power factor (higher = more weight near surface)",
    )

    # Void filtering - removes constraints far from point cloud data
    void_filter_enabled: bool = Field(
        default=True,
        description="Filter out constraints in void regions (far from point cloud)",
    )
    void_max_distance: float = Field(
        default=0.3,
        ge=0.05,
        le=2.0,
        description="Maximum distance from point cloud to keep a constraint",
    )


class GeneratedConstraint(BaseModel):
    """A constraint generated by auto-analysis, pending user approval.

    Wraps standard constraint data with algorithm metadata.
    """

    # The constraint itself (polymorphic - box, halfspace, pocket, etc.)
    constraint: dict = Field(..., description="Constraint data (type, sign, geometry)")

    # Metadata
    algorithm: AlgorithmType = Field(..., description="Algorithm that generated this")
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Algorithm's confidence in this constraint"
    )
    description: str = Field(..., description="Human-readable description")


class AlgorithmStats(BaseModel):
    """Statistics for a single algorithm's contribution."""

    constraints_generated: int = Field(0, description="Number of constraints from this algorithm")
    coverage_description: str = Field("", description="What this algorithm detected")


class AnalysisSummary(BaseModel):
    """Summary statistics for auto-analysis results."""

    total_constraints: int = Field(..., description="Total constraints generated")
    solid_constraints: int = Field(..., description="Constraints marking solid regions")
    empty_constraints: int = Field(..., description="Constraints marking empty regions")
    algorithms_contributing: int = Field(..., description="Number of algorithms that contributed")


class AutoAnalysisResult(BaseModel):
    """Complete auto-analysis result with generated constraints."""

    model_config = ConfigDict(ser_json_timedelta="iso8601")

    analysis_id: str = Field(..., description="Unique identifier for this analysis")
    computed_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="When analysis was performed",
    )
    algorithms_run: list[str] = Field(..., description="Algorithms that were executed")
    summary: AnalysisSummary = Field(..., description="Aggregated statistics")
    algorithm_stats: dict[str, AlgorithmStats] = Field(
        default_factory=dict, description="Per-algorithm statistics"
    )
    generated_constraints: list[GeneratedConstraint] = Field(
        default_factory=list, description="Constraints ready for user review"
    )


class AutoAnalyzeRequest(BaseModel):
    """Request parameters for auto-analysis."""

    algorithms: list[str] | None = Field(
        default=None,
        description="Algorithms to run (default: all). Options: pocket, normal_offset, flood_fill, voxel_regions, normal_idw",
    )
    recompute: bool = Field(
        default=False, description="Force recomputation even if cached results exist"
    )
    options: AutoAnalysisOptions = Field(
        default_factory=lambda: AutoAnalysisOptions(),
        description="Tunable hyperparameters for algorithms",
    )


class ApplyConstraintsRequest(BaseModel):
    """Request to apply selected generated constraints."""

    constraint_indices: list[int] = Field(
        ..., description="Indices of generated constraints to apply"
    )
